const illusies = [
  {
    naam: "De Müller-Lyer pijlen",
    beschrijving: "Welke lijn is langer — de bovenste of de onderste?",
    uitleg: "Ze zijn even lang! De pijlpunten aan het einde bedriegen je hersenen. Als de pijlen naar buiten wijzen, lijkt de lijn langer. Je hersenen gebruiken pijlen normaal als aanwijzingen voor diepte.",
    wikipedia: "Müller-Lyer_illusion",
    emoji: "↔️",
  },
  {
    naam: "De Necker kubus",
    beschrijving: "Kijk goed — welk vlak zit aan de voorkant van de kubus?",
    uitleg: "De kubus heeft geen echte voorkant! Je hersenen wisselen telkens van mening. Staar er even naar en plotseling 'flipt' de kubus. Dit heet een omkeerbare figuur.",
    wikipedia: "Necker_cube",
    emoji: "🎲",
  },
  {
    naam: "De Kanizsa driehoek",
    beschrijving: "Zie je een witte driehoek in het midden? Maar bestaat hij echt?",
    uitleg: "Er is geen driehoek! Je hersenen maken hem zelf. Drie taartpunten en drie hoeken zijn genoeg — je brein tekent de lijnen er zelf tussen. Dit heet een illusoire contour.",
    wikipedia: "Kanizsa_triangle",
    emoji: "🔺",
  },
  {
    naam: "De vaas van Rubin",
    beschrijving: "Zie je een vaas of twee gezichten die elkaar aankijken?",
    uitleg: "Beide zijn goed! Wit of zwart als achtergrond kiezen, doet je hersenen switchen tussen een vaas en twee gezichten. Je kunt niet beide tegelijk zien.",
    wikipedia: "Rubin_vase",
    emoji: "🏺",
  },
  {
    naam: "De Ponzo illusie",
    beschrijving: "Welke horizontale lijn is langer — de bovenste of de onderste?",
    uitleg: "Ze zijn even lang! De naar elkaar toe lopende lijnen doen je hersenen denken dat je in de verte kijkt. Dingen die 'ver weg' zijn en toch even groot lijken, schat je brein dan automatisch groter in.",
    wikipedia: "Ponzo_illusion",
    emoji: "🛤️",
  },
  {
    naam: "Het Hermann rooster",
    beschrijving: "Zie je grijze vlekjes op de kruispunten? Kijk dan recht naar één — is hij er dan nog?",
    uitleg: "De grijze vlekjes zijn er niet echt! Ze verdwijnen zodra je er direct naar kijkt. Cellen in je ogen remmen elkaars signalen af op de kruispunten, waardoor je brein iets ziet dat er niet is.",
    wikipedia: "Hermann_grid_illusion",
    emoji: "⬛",
  },
  {
    naam: "De café-muur",
    beschrijving: "Zijn de horizontale rijen recht of schuin?",
    uitleg: "Ze zijn volledig recht en parallel! De afwisselende lichte en donkere blokjes — verschoven per rij — laten je hersenen denken dat de lijnen schuin lopen. Een Britse wetenschapper ontdekte dit patroon op de muur van een café.",
    wikipedia: "Café_wall_illusion",
    emoji: "🏛️",
  },
  {
    naam: "De Penrose driehoek",
    beschrijving: "Dit ziet er uit als een echte driehoek — maar kun jij hem nabouwen?",
    uitleg: "Nee! De Penrose driehoek is onmogelijk in de echte wereld. Elke hoek klopt op zichzelf, maar samen zijn ze tegenstrijdig. Hij bestaat alleen op papier dankzij een slimme truc met perspectief.",
    wikipedia: "Penrose_triangle",
    emoji: "📐",
  },
  {
    naam: "De Penrose trap",
    beschrijving: "Kun jij zien waar de trap begint en eindigt?",
    uitleg: "Nergens! De trap gaat eeuwig omhoog — en ook eeuwig omlaag. Het is een oneindige lus. In het echt is hij onmogelijk te bouwen, maar op papier klopt elk hoekje afzonderlijk.",
    wikipedia: "Penrose_stairs",
    emoji: "🪜",
  },
  {
    naam: "Eend of konijn?",
    beschrijving: "Wat zie jij — een eend of een konijn?",
    uitleg: "Beide! Kijk je naar links, dan zie je een eend met een snavel. Kijk je naar rechts, dan zie je een konijn met oren. Je hersenen kunnen de afbeelding op twee manieren lezen — en wisselen er steeds van!",
    wikipedia: "Rabbit–duck_illusion",
    emoji: "🦆",
  },
  {
    naam: "Jong meisje of oude vrouw?",
    beschrijving: "Zie jij een jong meisje of een oude vrouw?",
    uitleg: "Beide zitten in de afbeelding. Het oor van de jonge vrouw is het oog van de oude. De kin van de jonge vrouw is de neus van de oude. Eens gezien, kun je niet meer kiezen welke je ziet!",
    wikipedia: "My_Wife_and_My_Mother-in-Law_(Hill)",
    emoji: "👩",
  },
  {
    naam: "De Zöllner lijnen",
    beschrijving: "Zijn de lange diagonale lijnen parallel aan elkaar?",
    uitleg: "Ja, ze zijn perfect parallel! Maar door de kleine streepjes die er schuin doorheen lopen, lijkt het alsof ze schuin staan. Je hersenen laten zich afleiden door de kleine details.",
    wikipedia: "Zöllner_illusion",
    emoji: "📏",
  },
  {
    naam: "De Ebbinghaus cirkels",
    beschrijving: "Welke oranje cirkel in het midden is groter?",
    uitleg: "Ze zijn even groot! De cirkel omgeven door kleine cirkels lijkt groter, en de cirkel omgeven door grote cirkels lijkt kleiner. Je hersenen schatten grootte altijd in vergelijking met de omgeving.",
    wikipedia: "Ebbinghaus_illusion",
    emoji: "⭕",
  },
  {
    naam: "De Fraser spiraal",
    beschrijving: "Zie je een spiraal die naar binnen draait?",
    uitleg: "Het zijn gewone cirkels! Geen enkele lijn raakt de volgende. De gedraaide streepjes in elk segment doen je hersenen geloven dat de cirkels een spiraal vormen. Als je één cirkel volgt met je vinger, kom je altijd terug waar je begon.",
    wikipedia: "Fraser_spiral",
    emoji: "🌀",
  },
  {
    naam: "De schaduwcontrole van Adelson",
    beschrijving: "Zijn vakje A en vakje B op het schaakbord even donker, of is een van de twee lichter?",
    uitleg: "Ze zijn precies even donker! Maar vakje B ligt in de schaduw van het groene blokje, waardoor je brein hem automatisch als lichter interpreteert. Je hersenen doen altijd aan schaduwcorrectie — zelfs als het niet nodig is.",
    wikipedia: "Checker_shadow_illusion",
    emoji: "♟️",
  },
  {
    naam: "De onmogelijke kubus",
    beschrijving: "Probeer de randen van deze kubus te volgen — kloppen ze?",
    uitleg: "Nee! De ribben van de kubus zijn verbonden op een manier die in het echt niet kan. Net als de Penrose driehoek klopt elk onderdeel afzonderlijk, maar samen vormen ze een onmogelijk object.",
    wikipedia: "Impossible_cube",
    emoji: "📦",
  },
  {
    naam: "De onmogelijke vork",
    beschrijving: "Tel de tanden van de vork aan de voorkant. Tel ze dan aan de achterkant. Klopt dat?",
    uitleg: "Nee! Aan de voorkant heeft de vork drie tanden, aan de achterkant zijn het er twee. Halverwege verdwijnt er een tand als bij toverslag. Je hersenen proberen het te repareren maar slagen er niet in.",
    wikipedia: "Blivet",
    emoji: "🍴",
  },
  {
    naam: "De holle driehoek",
    beschrijving: "Beweeg de afbeelding langzaam naar je gezicht. Wat zie je veranderen?",
    uitleg: "De driehoek die eerst ingedeukt leek, springt plotseling naar voren! Je hersenen beslissen steeds opnieuw welke kant 'voor' is. Dit is dezelfde truc als bij de Necker kubus.",
    wikipedia: "Hollow-Face_illusion",
    emoji: "🔄",
  },
  {
    naam: "De Jastrow figuren",
    beschrijving: "Zijn de twee banaan-vormen even groot?",
    uitleg: "Ja, ze zijn precies even groot! Maar de onderste lijkt altijd groter. Dit komt doordat je de langere buitenkant van de ene figuur vergelijkt met de kortere binnenkant van de andere.",
    wikipedia: "Jastrow_illusion",
    emoji: "🍌",
  },
  {
    naam: "De Ames kamer",
    beschrijving: "Kijk naar de twee personen in de kamer — waarom lijkt de ene zo veel groter?",
    uitleg: "De kamer is zelf de truc! Hij ziet er van voren rechthoekig uit, maar is in werkelijkheid schuin gebouwd. De persoon rechts staat vlak bij de kijker, de persoon links is ver weg — maar de kamer maskeert dat volledig.",
    wikipedia: "Ames_room",
    emoji: "🏠",
  },
  {
    naam: "De bewegende slangen",
    beschrijving: "Beweeg je ogen over de afbeelding. Wat lijken de cirkels te doen?",
    uitleg: "Ze lijken te draaien — maar de afbeelding staat stil! Kleine kleurverschillen en de manier waarop je ogen bewegen zorgen ervoor dat je brein beweging 'ziet'. Staar je ogen op één plek en ze stoppen.",
    wikipedia: "Rotating_snakes_illusion",
    emoji: "🐍",
  },
  {
    naam: "De Shepard tafels",
    beschrijving: "Welk tafelblad is langer — de linker of de rechter?",
    uitleg: "Ze zijn even groot! Als je ze uitknipt en naast elkaar legt, zijn ze identiek. Maar door de perspectief-lijnen van de tafelpoten lijkt de ene smal en lang, en de andere breed en kort.",
    wikipedia: "Shepard_tables",
    emoji: "🪑",
  },
  {
    naam: "De Poggendorff illusie",
    beschrijving: "De schuine lijn links verdwijnt achter een balk. Welke lijn rechts is de voortzetting?",
    uitleg: "Het lijkt de bovenste, maar het is de onderste! Je hersenen schatten hoeken slecht in als een lijn achter iets verdwijnt. Wiskundigen en piloten zijn getraind om dit te corrigeren.",
    wikipedia: "Poggendorff_illusion",
    emoji: "📉",
  },
  {
    naam: "De Hering illusie",
    beschrijving: "Zijn de twee rode horizontale lijnen recht of gebogen?",
    uitleg: "Ze zijn perfect recht! De uitwaaierende lijnen op de achtergrond doen je hersenen denken dat de rechte lijnen naar buiten buigen, alsof je door een visooglens kijkt.",
    wikipedia: "Hering_illusion",
    emoji: "🎯",
  },
  {
    naam: "De Titchener cirkels",
    beschrijving: "Zijn de twee oranje cirkels in het midden even groot?",
    uitleg: "Ja! Dit is dezelfde truc als de Ebbinghaus cirkels — de omringende cirkels bepalen hoe groot jij de middelste schat. Je brein kent geen absolute maten, alleen verhoudingen.",
    wikipedia: "Ebbinghaus_illusion",
    emoji: "🔵",
  },
  {
    naam: "De Orbison illusie",
    beschrijving: "Lijkt het vierkant in het midden vervormd?",
    uitleg: "Het is een perfect vierkant! De uitwaaierende lijnen op de achtergrond maken de rechte zijden van het vierkant gekromd lijken. Je hersenen passen de rechte lijnen aan aan de 'perspectief' van de achtergrond.",
    wikipedia: "Orbison_illusion",
    emoji: "🟦",
  },
  {
    naam: "De Waterval illusie",
    beschrijving: "Staar 30 seconden naar de bewegende waterval, kijk dan naar een stille muur. Wat zie je?",
    uitleg: "De muur lijkt omhoog te bewegen! Cellen in je ogen die 'neerwaartse beweging' detecteren zijn vermoeid geraakt. De cellen voor 'opwaartse beweging' overheersen nu even — en je ziet nep-beweging.",
    wikipedia: "Motion_aftereffect",
    emoji: "💧",
  },
  {
    naam: "De lila achtervolger",
    beschrijving: "Staar naar het zwarte kruis in het midden. Wat zie je rondgaan?",
    uitleg: "Je ziet een groen bolletje terwijl er alleen lila bolletjes zijn! De lila bolletjes verdwijnen één voor één. Waar ze verdwijnen ziet je brein — door tegenstelling — groen. Dan lijken alle lila bolletjes weg en blijft er een groen bolletje over.",
    wikipedia: "Lilac_chaser",
    emoji: "🟣",
  },
  {
    naam: "De Scintillerende grid",
    beschrijving: "Zie je zwarte vlekjes op de witte kruispunten? Kijk dan recht naar een kruispunt.",
    uitleg: "De zwarte vlekjes bestaan niet! Ze verschijnen en verdwijnen op de kruispunten die je niet direct aankijkt. Je ogen verwerken de randen van de kruispunten anders dan het midden, waardoor je brein vlekjes 'verzint'.",
    wikipedia: "Scintillating_grid_illusion",
    emoji: "✨",
  },
  {
    naam: "De Troxler vervaging",
    beschrijving: "Staar naar het midden van de afbeelding. Wat gebeurt er met de vlek aan de rand?",
    uitleg: "De vlek verdwijnt! Je ogen sturen alleen nieuwe informatie naar je brein. Als iets stilstaat en je er niet naar kijkt, stopt je brein er aandacht aan te besteden. Dit heet Troxler-vervaging.",
    wikipedia: "Troxler%27s_fading",
    emoji: "👁️",
  },
];

export default illusies;
