const jokes = [

  // DIEREN
  { setup: "Hoe ver loopt een hond het bos in?", punchline: "Halverwege — daarna loopt hij er weer UIT!" },
  { setup: "Wat doet een spin op de computer?", punchline: "Een website bouwen!" },
  { setup: "Hoe noem je een slapende stier?", punchline: "Een bul-dozer!" },
  { setup: "Wat krijg je als je een koe kruist met een octopus?", punchline: "Acht emmers melk tegelijk!" },
  { setup: "Hoe noem je een koe in een aardbeving?", punchline: "Een milkshake!" },
  { setup: "Waarom heeft een koe een bel?", punchline: "Omdat zijn hoorns het niet doen!" },
  { setup: "Wat zegt een koe als ze op vakantie gaat?", punchline: "Tot mooooooi!" },
  { setup: "Waarom studeert een egel nooit?", punchline: "Alles blijft toch aan hem hangen!" },
  { setup: "Wat doet een spin als hij boos is?", punchline: "Hij gaat door het lint!" },
  { setup: "Hoe noem je een kameel zonder bulten?", punchline: "Heel erg plat!" },
  { setup: "Waarom zingen vogels 's ochtends zo vroeg?", punchline: "Omdat de worm anders weg is!" },
  { setup: "Wat zegt een schildpad als hij haast heeft?", punchline: "Laat maar, ik ben toch te laat!" },
  { setup: "Hoe noem je een hond die goochelt?", punchline: "Een labra-goochelaar!" },
  { setup: "Waarom lopen katten altijd op hun tenen?", punchline: "Om de slapende honden niet wakker te maken!" },
  { setup: "Wat doet een mug in een wiskundeles?", punchline: "Optellen bij iedereen!" },
  { setup: "Waarom heeft een olifant zo'n goed geheugen?", punchline: "Omdat hij nooit vergeet hoe groot hij is!" },
  { setup: "Hoe noem je een grappige rups?", punchline: "Een kruip-comedian!" },
  { setup: "Wat doet een olifant in een Volkswagen?", punchline: "Zijn poten naar buiten steken!" },
  { setup: "Waarom praat een papegaai zo veel?", punchline: "Omdat er altijd wel iemand is die hem napraat!" },
  { setup: "Hoe noem je een kat die van wiskunde houdt?", punchline: "Een rekenpoes!" },
  { setup: "Wat zegt een slak die in de rij staat?", punchline: "Kom op mensen, ik heb niet eeuwig de tijd!" },
  { setup: "Waarom gaat een spin nooit op vakantie?", punchline: "Hij vindt altijd iets aan het web te doen!" },
  { setup: "Hoe noem je een vis die piano speelt?", punchline: "Een kla-vier-vis!" },
  { setup: "Waarom zijn eekhoorns altijd zo gestrest?", punchline: "Ze zijn altijd bang dat iemand hun noten pakt!" },
  { setup: "Wat doet een kip als het regent?", punchline: "Ze wordt nat — net als jij!" },
  { setup: "Hoe noem je een aap met een zonnebril?", punchline: "Een coole aap — gewoon!" },
  { setup: "Waarom gaan olifanten nooit op het strand?", punchline: "Ze passen niet in het zwembroekje!" },
  { setup: "Wat zegt een hond als zijn baas thuiskomt?", punchline: "Eindelijk! Ik stond hier al de héle dag!" },
  { setup: "Hoe noem je een koe die net een liedje zingt?", punchline: "Muuuuuzikaal!" },
  { setup: "Waarom heeft een olifant geen fiets?", punchline: "Omdat hij de bel niet kan vinden tussen zijn oren!" },

  // ETEN
  { setup: "Waarom lacht een aardbei altijd?", punchline: "Omdat hij altijd in de jam zit!" },
  { setup: "Wat zegt een ei tegen het andere ei?", punchline: "Jij bent ook niet gaar!" },
  { setup: "Hoe noem je een ijsje in de zon?", punchline: "Een grote plas!" },
  { setup: "Waarom werd de banaan naar de dokter gestuurd?", punchline: "Hij voelde zich niet lekker in zijn vel!" },
  { setup: "Wat zegt een koekje als het in de melk valt?", punchline: "Help, ik verdrink in het lekkerste bad ooit!" },
  { setup: "Hoe noem je een bang broodje?", punchline: "Een bibberham!" },
  { setup: "Waarom gaat een pizza nooit verloren?", punchline: "Iedereen weet altijd waar hij is!" },
  { setup: "Wat zegt een tomaat die struikelt?", punchline: "Plat!" },
  { setup: "Hoe noem je kaas die je niet zelf hebt gemaakt?", punchline: "Andermans kaas — maar ook lekker!" },
  { setup: "Waarom is soep altijd zo wijs?", punchline: "Omdat hij altijd lang staat te sudderen!" },
  { setup: "Wat zegt een friet die zich verveelt?", punchline: "Ik hang hier maar een beetje!" },
  { setup: "Hoe noem je een boom die appels maakt die je niet lekker vindt?", punchline: "Toch een appelboom — hij doet gewoon zijn best!" },
  { setup: "Waarom huilt een ui altijd?", punchline: "Omdat iedereen hem snijdt zodra hij in de buurt komt!" },
  { setup: "Wat is het lievelingseten van een wiskundeleraar?", punchline: "Taart — want die kun je in stukken verdelen!" },
  { setup: "Hoe noem je een vork die graag danst?", punchline: "Een party-vork!" },
  { setup: "Waarom is een worst nooit verdrietig?", punchline: "Hij zit altijd goed in zijn vel!" },
  { setup: "Wat zegt een snoepje als het opgesnoept wordt?", punchline: "Dit is heerlijk — maar ook mijn einde!" },
  { setup: "Hoe noem je een grappige pannenkoek?", punchline: "Een flap-ple!" },
  { setup: "Waarom is een boterham nooit saai?", punchline: "Hij zit altijd vol met van alles!" },
  { setup: "Wat zegt een komkommer als hij in de zon ligt?", punchline: "Lekker cool blijven!" },

  // SCHOOL
  { setup: "Wat is het lievelingsvak van een geest?", punchline: "Geo-GRAF-ie — want daar zit het woord 'graf' in!" },
  { setup: "Waarom at de leerling zijn huiswerk op?", punchline: "De juf zei dat het stukken beter kon!" },
  { setup: "Hoe noem je een leraar die altijd slaapt in de les?", punchline: "Moe-ster!" },
  { setup: "Wat is het verschil tussen een leraar en een trein?", punchline: "Een trein zegt 'instappen!' en een leraar zegt 'uitstappen!'" },
  { setup: "Waarom ging het potlood naar school?", punchline: "Het wilde scherper worden!" },
  { setup: "Hoe noem je een leerling die nooit te laat is?", punchline: "Ongelooflijk!" },
  { setup: "Waarom heeft de wiskundeleraar zoveel vrienden?", punchline: "Omdat hij altijd goed kan optellen!" },
  { setup: "Wat zegt een gum als hij klaar is?", punchline: "Dat is uitgewist!" },
  { setup: "Hoe noem je een potlood dat altijd liegt?", punchline: "Een be-drog-potlood!" },
  { setup: "Waarom doet een leerling zijn ogen dicht in de les?", punchline: "Om beter te horen!" },
  { setup: "Wat staat er op de deur van het lokaal van de aardrijkskunde-leraar?", punchline: "De wereld is van mij!" },
  { setup: "Hoe noem je een kind dat altijd alles weet?", punchline: "Irritant — maar ook handig!" },
  { setup: "Waarom is een schooltas altijd zo zwaar?", punchline: "Omdat hij het gewicht van alle kennis draagt!" },
  { setup: "Wat zegt een schrift na de zomervakantie?", punchline: "Ik ben er klaar voor... bijna!" },
  { setup: "Hoe noem je een wiskundeboek dat altijd huilt?", punchline: "Vol problemen!" },

  // SPORT
  { setup: "Waarom is een voetbal zo eerlijk?", punchline: "Hij trapt nooit terug!" },
  { setup: "Hoe noem je een tennisser die altijd wint?", punchline: "Een aas-speler!" },
  { setup: "Waarom zwemt een olifant niet graag?", punchline: "Zijn zwembroek zakt altijd af!" },
  { setup: "Wat zegt een bal die moe is?", punchline: "Ik moet even bijkomen!" },
  { setup: "Hoe noem je een keeper die nooit een bal tegenhoudt?", punchline: "Door-laat-je!" },
  { setup: "Waarom kan een fiets niet alleen staan?", punchline: "Omdat hij twee-wieler is!" },
  { setup: "Wat zegt een schaatser die valt?", punchline: "Ik deed het met opzet!" },
  { setup: "Hoe noem je een zwemmer zonder armen?", punchline: "Moe!" },
  { setup: "Waarom verliest een spook nooit bij verstoppertje?", punchline: "Omdat hij altijd door muren loopt!" },
  { setup: "Wat zegt een sportschoen als hij moe is?", punchline: "Ik houd het niet meer vol — ik ben uitgelopen!" },

  // FAMILIE
  { setup: "Waarom vertelt papa altijd dezelfde grappen?", punchline: "Omdat hij denkt dat ze de tweede keer beter worden!" },
  { setup: "Hoe noem je een broer die altijd gelijk heeft?", punchline: "Niet jouw broer!" },
  { setup: "Waarom heeft opa altijd gelijk?", punchline: "Omdat hij al zo lang oefent!" },
  { setup: "Wat zegt een baby-computer?", punchline: "Da-ta, da-ta!" },
  { setup: "Hoe noem je een zusje dat nooit stil is?", punchline: "Een geluids-installatie!" },
  { setup: "Waarom gaat oma nooit verloren?", punchline: "Iedereen helpt haar altijd de weg te vinden!" },
  { setup: "Wat is het verschil tussen een papa en een boek?", punchline: "Een boek kun je dichtslaan!" },
  { setup: "Hoe noem je een kind dat altijd zijn kamer opruimt?", punchline: "Een sprookje!" },
  { setup: "Waarom huilt een baby altijd?", punchline: "Hij kan nog niks anders!" },
  { setup: "Wat zegt een broer als hij zijn zus ziet gamen?", punchline: "Mag ik ook?" },

  // NATUUR EN WEER
  { setup: "Waarom regent het altijd in de vakantie?", punchline: "Omdat de zon ook vrij heeft!" },
  { setup: "Hoe noem je een boom die graag zingt?", punchline: "Een pop-ulier!" },
  { setup: "Wat zegt een wolk als hij boos is?", punchline: "Dan dondert het!" },
  { setup: "Waarom is de zee altijd zo rustig?", punchline: "Dat is hij niet — hij gaat altijd over zijn oevers!" },
  { setup: "Hoe noem je sneeuw die schreeuwt?", punchline: "IJskreet!" },
  { setup: "Wat zegt de wind als hij door een boom waait?", punchline: "Niets — hij fluistert alleen!" },
  { setup: "Waarom staat een cactus nooit te trillen?", punchline: "Hij is gewend aan de prik!" },
  { setup: "Hoe noem je een berg die graag danst?", punchline: "Een discotop!" },
  { setup: "Wat doet de zon als ze moe is?", punchline: "Ze gaat onder!" },
  { setup: "Waarom huilt het regenwoud zo veel?", punchline: "Dat is geen huilen — dat is regen!" },
  { setup: "Hoe noem je een druppel regen die haast heeft?", punchline: "Een spoed-bui!" },
  { setup: "Wat zegt een vulkaan als hij boos is?", punchline: "Ik kook van woede — letterlijk!" },
  { setup: "Waarom is gras altijd zo groen?", punchline: "Omdat het nooit oranje is geworden!" },
  { setup: "Hoe noem je een rivier die altijd liegt?", punchline: "Een krom-me sloot!" },
  { setup: "Wat doet een regenboog als het stopt met regenen?", punchline: "Hij verdwijnt — net zoals jouw excuses!" },

  // RUIMTE
  { setup: "Waarom gaan astronauten nooit op dieet?", punchline: "Ze wegen toch niks in de ruimte!" },
  { setup: "Wat zegt een planeet als ze bumpt tegen een andere?", punchline: "Sorry, ik zag je niet om de zon!" },
  { setup: "Hoe noem je een grappige maan?", punchline: "Een maantje-grap!" },
  { setup: "Waarom schijnt de zon zo vroeg op?", punchline: "Omdat ze anders te laat is!" },
  { setup: "Wat eet een zwart gat het liefst?", punchline: "Alles — en dan nog meer!" },
  { setup: "Hoe noem je een ster die graag zingt?", punchline: "Een popster — letterlijk!" },
  { setup: "Waarom heeft Mars zo'n rode kleur?", punchline: "Omdat hij rood aanloopt als hij de Aarde ziet!" },
  { setup: "Wat zegt een raket als hij opstart?", punchline: "Tot zo — of tot nooit meer!" },
  { setup: "Hoe noem je een astronaut met kiespijn?", punchline: "Een ruimte-pijn-lijk geval!" },
  { setup: "Waarom heeft de maan geen honger?", punchline: "Hij zit vol — hij is al zo rond!" },

  // TECHNOLOGIE
  { setup: "Waarom ging de computer naar de dokter?", punchline: "Hij had een virus!" },
  { setup: "Hoe noem je een robot die altijd huilt?", punchline: "Een roest-bot!" },
  { setup: "Waarom werkt een toetsenbord nooit over?", punchline: "Omdat hij al genoeg typen heeft!" },
  { setup: "Wat zegt een telefoon als hij bijna leeg is?", punchline: "Help, ik verzwak!" },
  { setup: "Hoe noem je een printer die altijd fout gaat?", punchline: "Gewoon een normale printer!" },
  { setup: "Waarom vertelt een computer geen grappen?", punchline: "Bang voor een crash!" },
  { setup: "Wat zegt een laadkabel die moe is?", punchline: "Ik hang er maar bij!" },
  { setup: "Hoe noem je een slimme koelkast?", punchline: "Eentje die jouw eten niet opeet!" },
  { setup: "Waarom heeft een robot zo weinig vrienden?", punchline: "Hij is te stijfkoppig!" },
  { setup: "Wat doet een computer als hij zich verveelt?", punchline: "Hij surft op het web!" },

  // MUZIEK
  { setup: "Hoe noem je een gitaar die altijd vals is?", punchline: "Een snaar-geval!" },
  { setup: "Waarom gaat een piano nooit op vakantie?", punchline: "Hij is bang dat zijn toetsen roesten!" },
  { setup: "Wat zegt een trommel als hij pijn heeft?", punchline: "Ik voel me geslagen!" },
  { setup: "Hoe noem je een trompet in de regen?", punchline: "Nat geluid!" },
  { setup: "Waarom speelt een kat nooit viool?", punchline: "Hij krabt altijd op de verkeerde snaar!" },
  { setup: "Wat zegt een microfoon op een feestje?", punchline: "Testen, testen — is dit ding aan?" },
  { setup: "Hoe noem je een lied dat niemand kent?", punchline: "Een stil-te!" },
  { setup: "Waarom luistert een olifant zo graag naar muziek?", punchline: "Hij heeft nu eenmaal grote oren!" },
  { setup: "Wat zegt een noot als ze valt?", punchline: "Dat was een valse start!" },
  { setup: "Hoe noem je een grappige trombonist?", punchline: "Iemand die altijd uitschuift!" },

  // SUPERHELDEN EN AVONTUUR
  { setup: "Waarom draagt een superheld altijd een cape?", punchline: "Omdat een pyjama er minder stoer uitziet!" },
  { setup: "Hoe noem je een superheld die altijd te laat is?", punchline: "Een bijna-held!" },
  { setup: "Waarom gaat een piraat nooit naar de kapper?", punchline: "Hij is bang voor de schaar!" },
  { setup: "Hoe noem je een ridder zonder zwaard?", punchline: "Een gewone man in een pak!" },
  { setup: "Waarom slaapt Dracula overdag?", punchline: "Omdat hij 's nachts werkt en dat is uitputtend!" },
  { setup: "Wat is het lievelingsvervoer van een tovenaar?", punchline: "Een be-zem-de weg!" },
  { setup: "Hoe noem je een ninja die altijd lacht?", punchline: "Een grin-ja!" },
  { setup: "Waarom heeft een geest geen vrienden?", punchline: "Iedereen loopt weg als hij eraan komt!" },
  { setup: "Wat eet een draak als hij honger heeft?", punchline: "Alles wat hij tegenkomt — en dan nog een keer!" },
  { setup: "Hoe noem je een Viking die graag kookt?", punchline: "Een plun-der-kok!" },

  // BEROEPEN
  { setup: "Waarom is een bakker zo'n goede vriend?", punchline: "Hij staat altijd voor je klaar — en hij heeft brood!" },
  { setup: "Hoe noem je een dokter die altijd zingt?", punchline: "Een dokter-oper!" },
  { setup: "Waarom is een schilder zo moe aan het einde van de dag?", punchline: "Hij heeft de hele dag gevlakt!" },
  { setup: "Hoe noem je een politieagent die graag danst?", punchline: "Een disco-agent!" },
  { setup: "Waarom is een slager zo vriendelijk?", punchline: "Hij wil zijn klanten niet afschrikken!" },
  { setup: "Hoe noem je een brandweerman die bang is voor vuur?", punchline: "Werkloos!" },
  { setup: "Waarom is een kapper altijd zo vrolijk?", punchline: "Zijn werk staat hem goed!" },
  { setup: "Hoe noem je een piloot die altijd verdwaalt?", punchline: "Een toeristische vlucht!" },
  { setup: "Waarom is een tuinman zo'n rustig persoon?", punchline: "Hij weet dat alles zijn tijd nodig heeft!" },
  { setup: "Hoe noem je een kok die altijd iets verbrandt?", punchline: "Consistent!" },

  // TRANSPORT
  { setup: "Waarom kon de auto niet starten?", punchline: "Hij had geen zin!" },
  { setup: "Hoe noem je een boot die altijd zinkt?", punchline: "Een onderzeeër in wording!" },
  { setup: "Waarom gaat een trein nooit te voet?", punchline: "Hij heeft geen voeten — alleen rails!" },
  { setup: "Hoe noem je een vliegtuig dat bang is voor hoogtes?", punchline: "Een bus!" },
  { setup: "Waarom heeft een fiets geen motor?", punchline: "Omdat hij wil dat jij het werk doet!" },
  { setup: "Wat zegt een auto als hij vast staat in de file?", punchline: "Dit gaat een lange dag worden!" },
  { setup: "Hoe noem je een raket die nooit aankomt?", punchline: "Een gemiste kans!" },
  { setup: "Waarom rijdt een slak nooit in een sportauto?", punchline: "Hij zou er toch niet mee overweg kunnen!" },
  { setup: "Wat zegt een boot als hij de haven binnenvaart?", punchline: "Eindelijk thuis!" },
  { setup: "Hoe noem je een fiets die altijd te laat is?", punchline: "Een langzame rijder!" },

  // WOORDGRAPPEN
  { setup: "Wat is altijd voor je maar zie je nooit?", punchline: "De toekomst!" },
  { setup: "Hoe meer je ervan neemt, hoe meer je achterlaat. Wat is het?", punchline: "Een voetafdruk!" },
  { setup: "Wat heeft handen maar kan niet klappen?", punchline: "Een klok!" },
  { setup: "Ik ben droog als ik natmaak, nat als ik droogmaak. Wat ben ik?", punchline: "Een handdoek!" },
  { setup: "Wat wordt groter naarmate je er meer van weghaalt?", punchline: "Een gat!" },
  { setup: "Ik heb een mond maar eet niets, een bed maar slaap niet. Wat ben ik?", punchline: "Een rivier!" },
  { setup: "Wat kun je breken zonder het aan te raken?", punchline: "Een belofte!" },
  { setup: "Ik heb vleugels maar kan niet vliegen, ik heb een staart maar ben geen dier. Wat ben ik?", punchline: "Een vliegtuig!" },
  { setup: "Wat heb je nodig om iets te zien wat niemand ooit gezien heeft?", punchline: "Een spiegel!" },
  { setup: "Ik ga altijd maar kom nooit aan. Wat ben ik?", punchline: "De horizon!" },
  { setup: "Wat valt altijd maar komt nooit aan?", punchline: "Regen in een tekenfilm!" },
  { setup: "Ik ben licht als een veertje maar de sterkste man kan me niet lang vasthouden. Wat ben ik?", punchline: "Adem!" },

  // EXTRA GRAPPEN
  { setup: "Waarom lacht een spiegel nooit?", punchline: "Hij doet alleen wat jij doet!" },
  { setup: "Hoe noem je een grappige deur?", punchline: "Een lach-klink!" },
  { setup: "Waarom gaat een boek nooit naar het strand?", punchline: "Omdat het bang is dat hij doorweekt raakt!" },
  { setup: "Hoe noem je een stoel die graag hardloopt?", punchline: "Een ren-bank!" },
  { setup: "Waarom is een trampoline altijd zo vrolijk?", punchline: "Hij springt van de ene grap op de andere!" },
  { setup: "Wat zegt een koelkast als je hem opent?", punchline: "Doe die deur dicht, het tocht!" },
  { setup: "Hoe noem je een grappige bezem?", punchline: "Een veg-comedian!" },
  { setup: "Waarom gaat een lamp nooit op vakantie?", punchline: "Hij wil altijd in het licht staan!" },
  { setup: "Wat zegt een horloge dat stilstaat?", punchline: "Ik neem even een pauze!" },
  { setup: "Hoe noem je een serieuze clown?", punchline: "Verwarrend!" },
  { setup: "Waarom huilt een paraplu nooit?", punchline: "Anderen doen dat al genoeg voor hem!" },
  { setup: "Wat zegt een potlood dat breekt?", punchline: "Dit is het einde — voor nu!" },
  { setup: "Hoe noem je een bank die graag vertelt?", punchline: "Een verhalenbank!" },
  { setup: "Waarom lacht een trap altijd?", punchline: "Iedereen gaat over hem heen!" },
  { setup: "Wat zegt een vork die verloren raakt?", punchline: "Ik zit er goed naast!" },
  { setup: "Hoe noem je een grappige emmer?", punchline: "Eentje met een gat erin!" },
  { setup: "Waarom zingt een bezem nooit vals?", punchline: "Hij veegt altijd het juiste pad!" },
  { setup: "Wat zegt een sleutel die zijn slot niet kan vinden?", punchline: "Dit klopt van geen kant!" },
  { setup: "Hoe noem je een gordijn dat graag danst?", punchline: "Een swing-doek!" },
  { setup: "Waarom is een mop nooit saai?", punchline: "Omdat hij anders geen mop meer is!" },
];

export default jokes;
